[tool.ruff]
line-length = 120
extend-exclude = ["logging.handlers"]

[tool.ruff.lint]
# Enable pycodestyle (`E`), Pyflakes (`F`), and other rules
select = ["E", "F", "B", "I", "N", "UP", "RUF"]
# Игнорировать ошибки импорта и другие правила
ignore = [
    "F403",  # Star imports
    "F405",  # Star imports
    "E501",  # Line too long
    "B008",
    "RUF001",
    "RUF002",
]

[tool.ruff.lint.per-file-ignores]
# Игнорировать определенные правила для определенных файлов
"__init__.py" = ["F401"]  # Игнорировать неиспользуемые импорты в __init__.py